// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmALWGaQdgsSCSfZUBNiRF4uCV1G8SLdY',
    appId: '1:855512306204:web:8cd31d8f76c25210f4c5d9',
    messagingSenderId: '855512306204',
    projectId: 'bargify-b876f',
    authDomain: 'bargify-b876f.firebaseapp.com',
    storageBucket: 'bargify-b876f.firebasestorage.app',
    measurementId: 'G-XS39FW5RFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYhbLB3KdE8obsyfYBUKOabldEOu8TmHM',
    appId: '1:855512306204:android:0792fa55d97dc147f4c5d9',
    messagingSenderId: '855512306204',
    projectId: 'bargify-b876f',
    storageBucket: 'bargify-b876f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGaJRy_mMePbhkPp0zw-3GOxKDsWaNHTc',
    appId: '1:855512306204:ios:b80e4729080f264cf4c5d9',
    messagingSenderId: '855512306204',
    projectId: 'bargify-b876f',
    storageBucket: 'bargify-b876f.firebasestorage.app',
    iosBundleId: 'com.example.bargify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGaJRy_mMePbhkPp0zw-3GOxKDsWaNHTc',
    appId: '1:855512306204:ios:b80e4729080f264cf4c5d9',
    messagingSenderId: '855512306204',
    projectId: 'bargify-b876f',
    storageBucket: 'bargify-b876f.firebasestorage.app',
    iosBundleId: 'com.example.bargify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmALWGaQdgsSCSfZUBNiRF4uCV1G8SLdY',
    appId: '1:855512306204:web:0126441a6684ed5af4c5d9',
    messagingSenderId: '855512306204',
    projectId: 'bargify-b876f',
    authDomain: 'bargify-b876f.firebaseapp.com',
    storageBucket: 'bargify-b876f.firebasestorage.app',
    measurementId: 'G-3DRM1X6XDY',
  );
}
